In [2]:
import geopandas as gpd
import zipfile
import os

# Path to the zip file and the specific geojson file
zip_path = "input/geoBoundaries-ARG-ADM2-all.zip"
geojson_file = "geoBoundaries-ARG-ADM2.geojson"

# Extract only the specified geojson file to a temporary location
with zipfile.ZipFile(zip_path, "r") as zf:
    zf.extract(geojson_file, "input/tmp")

geojson_path = os.path.join("input/tmp", geojson_file)

# Read with geopandas
gdf = gpd.read_file(geojson_path)
print(gdf.head())

       shapeName shapeISO                  shapeID shapeGroup shapeType  \
0         Arauco           61730980B43357395590927        ARG      ADM2
1   Tres Arroyos           61730980B62269269094219        ARG      ADM2
2      El Carmen           61730980B76568954927707        ARG      ADM2
3        Pinamar           61730980B99310691740446        ARG      ADM2
4  General Pinto           61730980B27788441407365        ARG      ADM2

                                            geometry
0  POLYGON ((-66.35296 -28.73289, -66.35298 -28.7...
1  POLYGON ((-59.83498 -38.23132, -59.83506 -38.2...
2  POLYGON ((-65.14063 -24.33221, -65.14072 -24.3...
3  POLYGON ((-56.90898 -37.18885, -56.90895 -37.1...
4  POLYGON ((-61.71047 -34.62683, -61.76956 -34.5...

In [3]:
gdf

,shapeName,shapeISO,shapeID,shapeGroup,shapeType,geometry
0,Arauco,,61730980B43357395590927,ARG,ADM2,"POLYGON ((-66.35296 -28.73289, -66.35298 -28.7..."
1,Tres Arroyos,,61730980B62269269094219,ARG,ADM2,"POLYGON ((-59.83498 -38.23132, -59.83506 -38.2..."
2,El Carmen,,61730980B76568954927707,ARG,ADM2,"POLYGON ((-65.14063 -24.33221, -65.14072 -24.3..."
3,Pinamar,,61730980B99310691740446,ARG,ADM2,"POLYGON ((-56.90898 -37.18885, -56.90895 -37.1..."
4,General Pinto,,61730980B27788441407365,ARG,ADM2,"POLYGON ((-61.71047 -34.62683, -61.76956 -34.5..."
...,...,...,...,...,...,...
520,San Pedro,,61730980B44314370056359,ARG,ADM2,"POLYGON ((-60.0243 -33.82662, -60.02422 -33.82..."
521,Iruya,,61730980B58435423783603,ARG,ADM2,"POLYGON ((-64.58476 -22.67584, -64.58488 -22.6..."
522,Santa Bárbara,,61730980B61196907081286,ARG,ADM2,"POLYGON ((-64.53339 -24.50532, -64.53265 -24.5..."
523,Suipacha,,61730980B93203446510136,ARG,ADM2,"POLYGON ((-59.8848 -34.61896, -59.93792 -34.66..."
524,Salto,,61730980B64997833188567,ARG,ADM2,"POLYGON ((-60.49667 -34.17665, -60.49575 -34.1..."